#!/bin/bash

usage()
{
    echo "    #############################
    earlGrey
    Required Parameters:
        -g == genome.fasta
        -s == species name
        -o == output directory
        -r == RepeatMasker search term (e.g arthropoda/eukarya)

    Optional Parameters:
        -t == Number of Threads (DO NOT specify more than are available)
        -l == Repbase species subset library (FASTA format)
        -i == Number of Iterations to BLAST, Extract, Extend - Only enter a number between 5 and 10 (Iteration outputs are 0-based!) (Default: 5)
        -f == Number flanking basepairs to extract (Default: 1000)
        -d == Maximum non-TE distance between annotations to consider a pair to be from the same cluster (100 is recommended)
	-h == Show help

    Example Usage:

    earlGrey -g bombyxMori.fasta -s bombyxMori -o /home/toby/bombyxMori/repeatAnnotation/ -r arthropoda -t 16


    Prerequisites - These must be configured prior to using Earl Grey:
        - RepeatMasker (Version 4.1.2)                                                                                                                                                                                                               - RepeatModeler (version 2.0.2)                                                                                                                                                                                                                                                                                                                                                                                                                                                       Ensure you have run the ./configure script from the earlGrey installation directory
    Ensure RepeatMasker has been configured with the desired repeat libraries (RepBase and Dfam 3.2 are recommended)

    Queries can be sent to:
    tb529@exeter.ac.uk

    Please make use of the GitHub Issues and Discussion Tabs at: https://github.com/TobyBaril/EarlGrey
    #############################"
}
    
# Subprocess Make Directories #
makeDirectory()
{
    directory=$(realpath ${directory})
    mkdir -p ${directory}/${species}EarlGrey/
    OUTDIR=${directory}/${species}EarlGrey
    mkdir -p $OUTDIR/${species}_RepeatMasker/
    mkdir -p $OUTDIR/${species}_Database/
    mkdir -p $OUTDIR/${species}_RepeatModeler/
    mkdir -p $OUTDIR/${species}_BLASTN/
    mkdir -p $OUTDIR/${species}_ExtractAlign/
    mkdir -p $OUTDIR/${species}_Curated_Library/
    mkdir -p $OUTDIR/${species}_Masked_de_novo_Repeats/
    mkdir -p $OUTDIR/${species}_RepeatMasker_Against_Custom_Library/
    mkdir -p $OUTDIR/${species}_RepeatLandscape/
    mkdir -p $OUTDIR/${species}_mergedRepeats/
    mkdir -p ${OUTDIR}/${species}_summaryFiles/
    mkdir -p $OUTDIR/${species}_clusTErs/
}
    
# Subprocess PrepGenome #
prepGenome()
{
    genome=$(realpath ${genome})
    if [ ! -f ${genome}.prep ] || [ ! -f ${genome}.dict ]; then
    	cp ${genome} ${genome}.bak && gzip -f ${genome}.bak 
    	sed -i '/>/ s/ .*//g' ${genome}
    	${SCRIPT_DIR}/headSwap.sh -i ${genome} -o ${genome}.prep
    	sed -i '/^>/! s/D/N/g;/^>/! s/V/N/g;/^>/! s/H/N/g;/^>/! s/B/N/g;/^>/! s/P/N/g;/^>/! s/E/N/g' ${genome}.prep
    	dict=${genome}.dict
    	genome=${genome}.prep
    else
    	dict=${genome}.dict
	genome=${genome}.prep
    fi
}

# Subprocess getRepeatMaskerFasta
getRepeatMaskerFasta()
{
    if [[ $RepSpec = *" "* ]]; then
    	echo "ERROR: You have entered a species name that contains a space, please use the NCBI TaxID rather than name. E.G In place of \"Homo sapiens\" use \"9606\""
	exit 2
    fi
    famdb.py -i $(which RepeatMasker | sed 's|/[^/]*$||g')/Libraries/RepeatMaskerLib.h5 families -f fasta_name --include-class-in-name -a -d $RepSpec > ${OUTDIR}/${species}_Curated_Library/${RepSpec}.RepeatMasker.lib
    RepSub=${OUTDIR}/${species}_Curated_Library/${RepSpec}.RepeatMasker.lib
}

# Subprocess firstMask
firstMask()
{
    cd ${OUTDIR}/${species}_RepeatMasker
    RepeatMasker -species $RepSpec -nolow -norna -lcambig -s -a -pa $ProcNum -dir $OUTDIR/${species}_RepeatMasker $genome
    if [ ! -f ${OUTDIR}/${species}_RepeatMasker/*.masked ]; then
    	echo "ERROR: RepeatMasker failed, please check logs. This is likely because of an invalid species search term, if issue persists please use NCBI Taxids (E.G Drosophila is replaced with 7125)"; exit 2
    fi
}

# Subprocess firstCustom
firstCustom()
{
    cd ${OUTDIR}/${species}_RepeatMasker
    RepeatMasker -lib $RepSub -nolow -norna -lcambig -s -a -pa $ProcNum -dir $OUTDIR/${species}_RepeatMasker $genome
    if [ ! -e "${OUTDIR}/${species}_RepeatMasker/*.masked" ]; then
    	echo "ERROR: RepeatMasker failed, please check logs and custom repeat FASTA file"; exit 2
    fi
}

# Subprocess buildDB
buildDB()
{
    cd ${OUTDIR}/${species}_Database
    BuildDatabase -name ${species} -engine ncbi ${OUTDIR}/${species}_RepeatMasker/*.masked
}

# Subprocess deNovo1
deNovo1()
{
    cd ${OUTDIR}/${species}_RepeatModeler
    RepeatModeler -engine ncbi -pa ${ProcNum} -database ${OUTDIR}/${species}_Database/${species}
    if [ ! -e ${OUTDIR}/${species}_Database/${species}-families.fa ]; then
        echo "ERROR: RepeatModeler Failed, Retrying with limit set as Round 5"
        RepeatModeler -engine ncbi -pa ${ProcNum} -database ${OUTDIR}/${species}_Database/${species} -genomeSampleSizeMax 81000000
	if [ ! -e ${OUTDIR}/${species}_Database/${species}-families.fa ]; then
		echo "ERROR: RepeatModeler Failed, Retrying with limit set as Round 4"
		RepeatModeler -engine ncbi -pa ${ProcNum} -database ${OUTDIR}/${species}_Database/${species} -genomeSampleSizeMax 27000000
		if [ ! -e ${OUTDIR}/${species}_Database/${species}-families.fa ]; then
			echo "ERROR: RepeatModeler Failed"
			exit 2
		fi
	fi
    fi
}

# Subprocess moveFiles
moveFiles()
{
    cp ${OUTDIR}/${species}_Database/${species}-families.fa ${OUTDIR}/${species}_RepeatModeler/${species}-families.fa
}

# Subprocess clusterDeNovo
clusterDeNovo()
{
    cd-hit-est -d 0 -aS 0.8 -c 0.8 -G 0 -g 1 -b 500 -r 1 -i ${OUTDIR}/${species}_RepeatModeler/${species}-families.fa -o ${OUTDIR}/${species}_RepeatModeler/${species}-families.fa.filtered
}

# Subprocess BEE1
BEE1()
{
    cd ${OUTDIR}/${species}_BLASTN/
    blastn -query ${OUTDIR}/${species}_RepeatModeler/${species}-families.fa.filtered -subject ${genome} -out ${OUTDIR}/${species}_BLASTN/${species}_BLAST -evalue 1e-50 -outfmt "6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore"
}
 
# Subprocess Format1
Format1()
{
    cd ${OUTDIR}/${species}_RepeatModeler/
    cp ${species}-families.fa.filtered ${species}-families.fa.filtered.no_slash
    sed -i 's#/#___#g; s/#/__/g' ${species}-families.fa.filtered.no_slash

    cd ${OUTDIR}/${species}_BLASTN/
    cp ${species}_BLAST ${species}_BLAST.no_slash
    sed -i 's#/#___#g; s/#/__/g' ${species}_BLAST.no_slash
}

# Subprocess BEE2
BEE2()
{
    cd ${OUTDIR}/${species}_ExtractAlign
    python ${SCRIPT_DIR}/extract_align.py -g ${genome} -b ${OUTDIR}/${species}_BLASTN/${species}_BLAST.no_slash -l ${OUTDIR}/${species}_RepeatModeler/${species}-families.fa.filtered.no_slash -lb $Flank -rb $Flank -n 20 -a n -t n -e n
    mkdir ${OUTDIR}/${species}_ExtractAlign/mafft/ 
    parallel --jobs ${ProcNum} "mafft --auto {} > ${OUTDIR}/${species}_ExtractAlign/mafft/{/.}.mafft" ::: ${OUTDIR}/${species}_ExtractAlign/catTEfiles/*.fa 
    mkdir ${OUTDIR}/${species}_ExtractAlign/trimal/ && cd ${OUTDIR}/${species}_ExtractAlign/trimal/
    parallel --jobs ${ProcNum} "trimal -in {} -gt 0.6 -fasta -out ${OUTDIR}/${species}_ExtractAlign/trimal/{/.}.trimal.fa" ::: ${OUTDIR}/${species}_ExtractAlign/mafft/*.mafft
    mkdir ${OUTDIR}/${species}_ExtractAlign/embossCons/ && cd ${OUTDIR}/${species}_ExtractAlign/embossCons/
    parallel --jobs ${ProcNum} "cons -sequence {} -outseq ${OUTDIR}/${species}_ExtractAlign/embossCons/{/.}_cons.fa -name {/.}  -plurality 3 -identity 3" ::: ${OUTDIR}/${species}_ExtractAlign/trimal/*.trimal.fa
}

# Subprocess BEE3
BEE3()
{
    parallel --jobs ${ProcNum} "sed -i '/^>/ s/.trimal.*//g' {}" ::: ${OUTDIR}/${species}_ExtractAlign/embossCons/*_cons.fa
    cat ${OUTDIR}/${species}_ExtractAlign/embossCons/*_cons.fa > ${OUTDIR}/${species}_Curated_Library/${species}_de_novo_repeat_library_iter0.fasta
}

# Subprocess Iterations
Iterations()
{
    stage="Running BLAST, Extract, Extend Iteration 1"
    runningCow
    blastn -query ${OUTDIR}/${species}_Curated_Library/${species}_de_novo_repeat_library_iter0.fasta -subject ${genome} -out ${OUTDIR}/${species}_BLASTN/${species}_BLAST_iter1 -evalue 1e-50 -outfmt "6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore"
    cd ${OUTDIR}/${species}_ExtractAlign
    mkdir ${OUTDIR}/${species}_ExtractAlign/iter1
    cd ${OUTDIR}/${species}_ExtractAlign/iter1
    python ${SCRIPT_DIR}/extract_align.py -g ${genome} -b ${OUTDIR}/${species}_BLASTN/${species}_BLAST_iter1 -l ${OUTDIR}/${species}_Curated_Library/${species}_de_novo_repeat_library_iter0.fasta -lb $Flank -rb $Flank -n 20 -a n -t n -e n
    mkdir ${OUTDIR}/${species}_ExtractAlign/iter1/mafft/
    parallel --jobs ${ProcNum} "mafft --auto {} > ${OUTDIR}/${species}_ExtractAlign/iter1/mafft/{/.}.mafft" ::: ${OUTDIR}/${species}_ExtractAlign/iter1/catTEfiles/*.fa 
    mkdir ${OUTDIR}/${species}_ExtractAlign/iter1/trimal/
    parallel --jobs ${ProcNum} "trimal -in {} -gt 0.6 -fasta -out ${OUTDIR}/${species}_ExtractAlign/iter1/trimal/{/.}.trimal.fa" ::: ${OUTDIR}/${species}_ExtractAlign/iter1/mafft/*.mafft
    mkdir ${OUTDIR}/${species}_ExtractAlign/iter1/embossCons/
    parallel --jobs ${ProcNum} "cons -sequence {} -outseq ${OUTDIR}/${species}_ExtractAlign/iter1/embossCons/{/.}_cons.fa -name {/.}  -plurality 3 -identity 3" ::: ${OUTDIR}/${species}_ExtractAlign/iter1/trimal/*.trimal.fa
    parallel --jobs ${ProcNum} "sed -i '/^>/ s/.trimal.*//g' {}" ::: ${OUTDIR}/${species}_ExtractAlign/iter1/embossCons/*_cons.fa
    cat ${OUTDIR}/${species}_ExtractAlign/iter1/embossCons/*_cons.fa > ${OUTDIR}/${species}_Curated_Library/${species}_de_novo_repeat_library_iter1.fasta
    
    stage="Running BLAST, Extract, Extend Iteration 2"
    runningCow
    blastn -query ${OUTDIR}/${species}_Curated_Library/${species}_de_novo_repeat_library_iter1.fasta -subject ${genome} -out ${OUTDIR}/${species}_BLASTN/${species}_BLAST_iter2 -evalue 1e-50 -outfmt "6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore"
    cd ${OUTDIR}/${species}_ExtractAlign
    mkdir ${OUTDIR}/${species}_ExtractAlign/iter2
    cd ${OUTDIR}/${species}_ExtractAlign/iter2
    python ${SCRIPT_DIR}/extract_align.py -g ${genome} -b ${OUTDIR}/${species}_BLASTN/${species}_BLAST_iter2 -l ${OUTDIR}/${species}_Curated_Library/${species}_de_novo_repeat_library_iter1.fasta -lb $Flank -rb $Flank -n 20 -a n -t n -e n
    mkdir ${OUTDIR}/${species}_ExtractAlign/iter2/mafft/
    parallel --jobs ${ProcNum} "mafft --auto {} > ${OUTDIR}/${species}_ExtractAlign/iter2/mafft/{/.}.mafft" ::: ${OUTDIR}/${species}_ExtractAlign/iter2/catTEfiles/*.fa 
    mkdir ${OUTDIR}/${species}_ExtractAlign/iter2/trimal/
    parallel --jobs ${ProcNum} "trimal -in {} -gt 0.6 -fasta -out ${OUTDIR}/${species}_ExtractAlign/iter2/trimal/{/.}.trimal.fa" ::: ${OUTDIR}/${species}_ExtractAlign/iter2/mafft/*.mafft
    mkdir ${OUTDIR}/${species}_ExtractAlign/iter2/embossCons/
    parallel --jobs ${ProcNum} "cons -sequence {} -outseq ${OUTDIR}/${species}_ExtractAlign/iter2/embossCons/{/.}_cons.fa -name {/.}  -plurality 3 -identity 3" ::: ${OUTDIR}/${species}_ExtractAlign/iter2/trimal/*.trimal.fa
    parallel --jobs ${ProcNum} "sed -i '/^>/ s/.trimal.*//g' {}" ::: ${OUTDIR}/${species}_ExtractAlign/iter2/embossCons/*_cons.fa
    cat ${OUTDIR}/${species}_ExtractAlign/iter2/embossCons/*_cons.fa > ${OUTDIR}/${species}_Curated_Library/${species}_de_novo_repeat_library_iter2.fasta
    latestFile=${OUTDIR}/${species}_Curated_Library/${species}_de_novo_repeat_library_iter2.fasta
    
    if [ $num -gt 3 ]
        then
            stage="Running BLAST, Extract, Extend Iteration 3"
    	    runningCow
   	    blastn -query ${OUTDIR}/${species}_Curated_Library/${species}_de_novo_repeat_library_iter2.fasta -subject ${genome} -out ${OUTDIR}/${species}_BLASTN/${species}_BLAST_iter3 -evalue 1e-50 -outfmt "6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore"
    	    cd ${OUTDIR}/${species}_ExtractAlign
    	    mkdir ${OUTDIR}/${species}_ExtractAlign/iter3
    	    cd ${OUTDIR}/${species}_ExtractAlign/iter3
    	    python ${SCRIPT_DIR}/extract_align.py -g ${genome} -b ${OUTDIR}/${species}_BLASTN/${species}_BLAST_iter3 -l ${OUTDIR}/${species}_Curated_Library/${species}_de_novo_repeat_library_iter2.fasta -lb $Flank -rb $Flank -n 20 -a n -t n -e n
    	    mkdir ${OUTDIR}/${species}_ExtractAlign/iter3/mafft/
    	    parallel --jobs ${ProcNum} "mafft --auto {} > ${OUTDIR}/${species}_ExtractAlign/iter3/mafft/{/.}.mafft" ::: ${OUTDIR}/${species}_ExtractAlign/iter3/catTEfiles/*.fa 
    	    mkdir ${OUTDIR}/${species}_ExtractAlign/iter3/trimal/
    	    parallel --jobs ${ProcNum} "trimal -in {} -gt 0.6 -fasta -out ${OUTDIR}/${species}_ExtractAlign/iter3/trimal/{/.}.trimal.fa" ::: ${OUTDIR}/${species}_ExtractAlign/iter3/mafft/*.mafft
    	    mkdir ${OUTDIR}/${species}_ExtractAlign/iter3/embossCons/
    	    parallel --jobs ${ProcNum} "cons -sequence {} -outseq ${OUTDIR}/${species}_ExtractAlign/iter3/embossCons/{/.}_cons.fa -name {/.}  -plurality 3 -identity 3" ::: ${OUTDIR}/${species}_ExtractAlign/iter3/trimal/*.trimal.fa
    	    parallel --jobs ${ProcNum} "sed -i '/^>/ s/.trimal.*//g' {}" ::: ${OUTDIR}/${species}_ExtractAlign/iter3/embossCons/*_cons.fa
    	    cat ${OUTDIR}/${species}_ExtractAlign/iter3/embossCons/*_cons.fa > ${OUTDIR}/${species}_Curated_Library/${species}_de_novo_repeat_library_iter3.fasta
    	    latestFile=${OUTDIR}/${species}_Curated_Library/${species}_de_novo_repeat_library_iter3.fasta
	else
	    echo "$num iteractions complete"
    fi
    
    if [ $num -gt 4 ]
        then
            stage="Running BLAST, Extract, Extend Iteration 4"
            runningCow
            blastn -query ${OUTDIR}/${species}_Curated_Library/${species}_de_novo_repeat_library_iter3.fasta -subject ${genome} -out ${OUTDIR}/${species}_BLASTN/${species}_BLAST_iter4 -evalue 1e-50 -outfmt "6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore"
            cd ${OUTDIR}/${species}_ExtractAlign
            mkdir ${OUTDIR}/${species}_ExtractAlign/iter4
            cd ${OUTDIR}/${species}_ExtractAlign/iter4
            python ${SCRIPT_DIR}/extract_align.py -g ${genome} -b ${OUTDIR}/${species}_BLASTN/${species}_BLAST_iter4 -l ${OUTDIR}/${species}_Curated_Library/${species}_de_novo_repeat_library_iter3.fasta -lb $Flank -rb $Flank -n 20 -a n -t n -e n
            mkdir ${OUTDIR}/${species}_ExtractAlign/iter4/mafft/
            parallel --jobs ${ProcNum} "mafft --auto {} > ${OUTDIR}/${species}_ExtractAlign/iter4/mafft/{/.}.mafft" ::: ${OUTDIR}/${species}_ExtractAlign/iter4/catTEfiles/*.fa 
            mkdir ${OUTDIR}/${species}_ExtractAlign/iter4/trimal/
            parallel --jobs ${ProcNum} "trimal -in {} -gt 0.6 -fasta -out ${OUTDIR}/${species}_ExtractAlign/iter4/trimal/{/.}.trimal.fa" ::: ${OUTDIR}/${species}_ExtractAlign/iter4/mafft/*.mafft
            mkdir ${OUTDIR}/${species}_ExtractAlign/iter4/embossCons/
            parallel --jobs ${ProcNum} "cons -sequence {} -outseq ${OUTDIR}/${species}_ExtractAlign/iter4/embossCons/{/.}_cons.fa -name {/.}  -plurality 3 -identity 3" ::: ${OUTDIR}/${species}_ExtractAlign/iter4/trimal/*.trimal.fa
            parallel --jobs ${ProcNum} "sed -i '/^>/ s/.trimal.*//g' {}" ::: ${OUTDIR}/${species}_ExtractAlign/iter4/embossCons/*_cons.fa
            cat ${OUTDIR}/${species}_ExtractAlign/iter4/embossCons/*_cons.fa > ${OUTDIR}/${species}_Curated_Library/${species}_de_novo_repeat_library_iter4.fasta
            latestFile=${OUTDIR}/${species}_Curated_Library/${species}_de_novo_repeat_library_iter4.fasta
        else
            echo "$num iterations complete"
    fi
    
    if [ $num -gt 5 ]
        then
            stage="Running BLAST, Extract, Extend Iteration 5"
            runningCow
            blastn -query ${OUTDIR}/${species}_Curated_Library/${species}_de_novo_repeat_library_iter4.fasta -subject ${genome} -out ${OUTDIR}/${species}_BLASTN/${species}_BLAST_iter5 -evalue 1e-50 -outfmt "6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore"
            cd ${OUTDIR}/${species}_ExtractAlign
            mkdir ${OUTDIR}/${species}_ExtractAlign/iter5
            cd ${OUTDIR}/${species}_ExtractAlign/iter5
            python ${SCRIPT_DIR}/extract_align.py -g ${genome} -b ${OUTDIR}/${species}_BLASTN/${species}_BLAST_iter5 -l ${OUTDIR}/${species}_Curated_Library/${species}_de_novo_repeat_library_iter4.fasta -lb $Flank -rb $Flank -n 20 -a n -t n -e n
            mkdir ${OUTDIR}/${species}_ExtractAlign/iter5/mafft/
            parallel --jobs ${ProcNum} "mafft --auto {} > ${OUTDIR}/${species}_ExtractAlign/iter5/mafft/{/.}.mafft" ::: ${OUTDIR}/${species}_ExtractAlign/iter5/catTEfiles/*.fa 
            mkdir ${OUTDIR}/${species}_ExtractAlign/iter5/trimal/
            parallel --jobs ${ProcNum} "trimal -in {} -gt 0.6 -fasta -out ${OUTDIR}/${species}_ExtractAlign/iter5/trimal/{/.}.trimal.fa" ::: ${OUTDIR}/${species}_ExtractAlign/iter5/mafft/*.mafft
            mkdir ${OUTDIR}/${species}_ExtractAlign/iter5/embossCons/
            parallel --jobs ${ProcNum} "cons -sequence {} -outseq ${OUTDIR}/${species}_ExtractAlign/iter5/embossCons/{/.}_cons.fa -name {/.}  -plurality 3 -identity 3" ::: ${OUTDIR}/${species}_ExtractAlign/iter5/trimal/*.trimal.fa
            parallel --jobs ${ProcNum} "sed -i '/^>/ s/.trimal.*//g' {}" ::: ${OUTDIR}/${species}_ExtractAlign/iter5/embossCons/*_cons.fa
            cat ${OUTDIR}/${species}_ExtractAlign/iter5/embossCons/*_cons.fa > ${OUTDIR}/${species}_Curated_Library/${species}_de_novo_repeat_library_iter5.fasta
            latestFile=${OUTDIR}/${species}_Curated_Library/${species}_de_novo_repeat_library_iter5.fasta
        else
            echo "$num iterations complete"
    fi
    
    if [ $num -gt 6 ]
        then
            stage="Running BLAST, Extract, Extend Iteration 6"
            runningCow
            blastn -query ${OUTDIR}/${species}_Curated_Library/${species}_de_novo_repeat_library_iter5.fasta -subject ${genome} -out ${OUTDIR}/${species}_BLASTN/${species}_BLAST_iter6 -evalue 1e-50 -outfmt "6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore"
            cd ${OUTDIR}/${species}_ExtractAlign
            mkdir ${OUTDIR}/${species}_ExtractAlign/iter6
            cd ${OUTDIR}/${species}_ExtractAlign/iter6
            python ${SCRIPT_DIR}/extract_align.py -g ${genome} -b ${OUTDIR}/${species}_BLASTN/${species}_BLAST_iter6 -l ${OUTDIR}/${species}_Curated_Library/${species}_de_novo_repeat_library_iter5.fasta -lb $Flank -rb $Flank -n 20 -a n -t n -e n
            mkdir ${OUTDIR}/${species}_ExtractAlign/iter6/mafft/
            parallel --jobs ${ProcNum} "mafft --auto {} > ${OUTDIR}/${species}_ExtractAlign/iter6/mafft/{/.}.mafft" ::: ${OUTDIR}/${species}_ExtractAlign/iter6/catTEfiles/*.fa 
            mkdir ${OUTDIR}/${species}_ExtractAlign/iter6/trimal/
            parallel --jobs ${ProcNum} "trimal -in {} -gt 0.6 -fasta -out ${OUTDIR}/${species}_ExtractAlign/iter6/trimal/{/.}.trimal.fa" ::: ${OUTDIR}/${species}_ExtractAlign/iter6/mafft/*.mafft
            mkdir ${OUTDIR}/${species}_ExtractAlign/iter6/embossCons/
            parallel --jobs ${ProcNum} "cons -sequence {} -outseq ${OUTDIR}/${species}_ExtractAlign/iter6/embossCons/{/.}_cons.fa -name {/.}  -plurality 3 -identity 3" ::: ${OUTDIR}/${species}_ExtractAlign/iter6/trimal/*.trimal.fa
            parallel --jobs ${ProcNum} "sed -i '/^>/ s/.trimal.*//g' {}" ::: ${OUTDIR}/${species}_ExtractAlign/iter6/embossCons/*_cons.fa
            cat ${OUTDIR}/${species}_ExtractAlign/iter6/embossCons/*_cons.fa > ${OUTDIR}/${species}_Curated_Library/${species}_de_novo_repeat_library_iter6.fasta
            latestFile=${OUTDIR}/${species}_Curated_Library/${species}_de_novo_repeat_library_iter6.fasta
        else
            echo "$num iterations complete"
    fi
    
    
    if [ $num -gt 7 ]
        then
            stage="Running BLAST, Extract, Extend Iteration 7"
            runningCow
            blastn -query ${OUTDIR}/${species}_Curated_Library/${species}_de_novo_repeat_library_iter6.fasta -subject ${genome} -out ${OUTDIR}/${species}_BLASTN/${species}_BLAST_iter7 -evalue 1e-50 -outfmt "6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore"
            cd ${OUTDIR}/${species}_ExtractAlign
            mkdir ${OUTDIR}/${species}_ExtractAlign/iter7
            cd ${OUTDIR}/${species}_ExtractAlign/iter7
            python ${SCRIPT_DIR}/extract_align.py -g ${genome} -b ${OUTDIR}/${species}_BLASTN/${species}_BLAST_iter7 -l ${OUTDIR}/${species}_Curated_Library/${species}_de_novo_repeat_library_iter6.fasta -lb $Flank -rb $Flank -n 20 -a n -t n -e n
            mkdir ${OUTDIR}/${species}_ExtractAlign/iter7/mafft/
            parallel --jobs ${ProcNum} "mafft --auto {} > ${OUTDIR}/${species}_ExtractAlign/iter7/mafft/{/.}.mafft" ::: ${OUTDIR}/${species}_ExtractAlign/iter7/catTEfiles/*.fa 
            mkdir ${OUTDIR}/${species}_ExtractAlign/iter7/trimal/
            parallel --jobs ${ProcNum} "trimal -in {} -gt 0.6 -fasta -out ${OUTDIR}/${species}_ExtractAlign/iter7/trimal/{/.}.trimal.fa" ::: ${OUTDIR}/${species}_ExtractAlign/iter7/mafft/*.mafft
            mkdir ${OUTDIR}/${species}_ExtractAlign/iter7/embossCons/
            parallel --jobs ${ProcNum} "cons -sequence {} -outseq ${OUTDIR}/${species}_ExtractAlign/iter7/embossCons/{/.}_cons.fa -name {/.}  -plurality 3 -identity 3" ::: ${OUTDIR}/${species}_ExtractAlign/iter7/trimal/*.trimal.fa
            parallel --jobs ${ProcNum} "sed -i '/^>/ s/.trimal.*//g' {}" ::: ${OUTDIR}/${species}_ExtractAlign/iter7/embossCons/*_cons.fa
            cat ${OUTDIR}/${species}_ExtractAlign/iter7/embossCons/*_cons.fa > ${OUTDIR}/${species}_Curated_Library/${species}_de_novo_repeat_library_iter7.fasta
            latestFile=${OUTDIR}/${species}_Curated_Library/${species}_de_novo_repeat_library_iter7.fasta
        else
            echo "$num iterations complete"
    fi
    
    if [ $num -gt 8 ]
        then
            stage="Running BLAST, Extract, Extend Iteration 8"
            runningCow
            blastn -query ${OUTDIR}/${species}_Curated_Library/${species}_de_novo_repeat_library_iter7.fasta -subject ${genome} -out ${OUTDIR}/${species}_BLASTN/${species}_BLAST_iter8 -evalue 1e-50 -outfmt "6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore"
            cd ${OUTDIR}/${species}_ExtractAlign
            mkdir ${OUTDIR}/${species}_ExtractAlign/iter8
            cd ${OUTDIR}/${species}_ExtractAlign/iter8
            python ${SCRIPT_DIR}/extract_align.py -g ${genome} -b ${OUTDIR}/${species}_BLASTN/${species}_BLAST_iter8 -l ${OUTDIR}/${species}_Curated_Library/${species}_de_novo_repeat_library_iter7.fasta -lb $Flank -rb $Flank -n 20 -a n -t n -e n
            mkdir ${OUTDIR}/${species}_ExtractAlign/iter8/mafft/
            parallel --jobs ${ProcNum} "mafft --auto {} > ${OUTDIR}/${species}_ExtractAlign/iter8/mafft/{/.}.mafft" ::: ${OUTDIR}/${species}_ExtractAlign/iter8/catTEfiles/*.fa 
            mkdir ${OUTDIR}/${species}_ExtractAlign/iter8/trimal/
            parallel --jobs ${ProcNum} "trimal -in {} -gt 0.6 -fasta -out ${OUTDIR}/${species}_ExtractAlign/iter8/trimal/{/.}.trimal.fa" ::: ${OUTDIR}/${species}_ExtractAlign/iter8/mafft/*.mafft
            mkdir ${OUTDIR}/${species}_ExtractAlign/iter8/embossCons/
            parallel --jobs ${ProcNum} "cons -sequence {} -outseq ${OUTDIR}/${species}_ExtractAlign/iter8/embossCons/{/.}_cons.fa -name {/.}  -plurality 3 -identity 3" ::: ${OUTDIR}/${species}_ExtractAlign/iter8/trimal/*.trimal.fa
            parallel --jobs ${ProcNum} "sed -i '/^>/ s/.trimal.*//g' {}" ::: ${OUTDIR}/${species}_ExtractAlign/iter8/embossCons/*_cons.fa
            cat ${OUTDIR}/${species}_ExtractAlign/iter8/embossCons/*_cons.fa > ${OUTDIR}/${species}_Curated_Library/${species}_de_novo_repeat_library_iter8.fasta
            latestFile=${OUTDIR}/${species}_Curated_Library/${species}_de_novo_repeat_library_iter8.fasta
        else
            echo "$num iterations complete"
    fi
    
    if [ $num -gt 9 ]
        then
            stage="Running BLAST, Extract, Extend Iteration 9"
            runningCow
            blastn -query ${OUTDIR}/${species}_Curated_Library/${species}_de_novo_repeat_library_iter8.fasta -subject ${genome} -out ${OUTDIR}/${species}_BLASTN/${species}_BLAST_iter9 -evalue 1e-50 -outfmt "6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore"
            cd ${OUTDIR}/${species}_ExtractAlign
            mkdir ${OUTDIR}/${species}_ExtractAlign/iter9
            cd ${OUTDIR}/${species}_ExtractAlign/iter9
            python ${SCRIPT_DIR}/extract_align.py -g ${genome} -b ${OUTDIR}/${species}_BLASTN/${species}_BLAST_iter9 -l ${OUTDIR}/${species}_Curated_Library/${species}_de_novo_repeat_library_iter8.fasta -lb $Flank -rb $Flank -n 20 -a n -t n -e n
            mkdir ${OUTDIR}/${species}_ExtractAlign/iter9/mafft/
            parallel --jobs ${ProcNum} "mafft --auto {} > ${OUTDIR}/${species}_ExtractAlign/iter9/mafft/{/.}.mafft" ::: ${OUTDIR}/${species}_ExtractAlign/iter9/catTEfiles/*.fa 
            mkdir ${OUTDIR}/${species}_ExtractAlign/iter9/trimal/
            parallel --jobs ${ProcNum} "trimal -in {} -gt 0.6 -fasta -out ${OUTDIR}/${species}_ExtractAlign/iter9/trimal/{/.}.trimal.fa" ::: ${OUTDIR}/${species}_ExtractAlign/iter9/mafft/*.mafft
            mkdir ${OUTDIR}/${species}_ExtractAlign/iter9/embossCons/
            parallel --jobs ${ProcNum} "cons -sequence {} -outseq ${OUTDIR}/${species}_ExtractAlign/iter9/embossCons/{/.}_cons.fa -name {/.}  -plurality 3 -identity 3" ::: ${OUTDIR}/${species}_ExtractAlign/iter9/trimal/*.trimal.fa
            parallel --jobs ${ProcNum} "sed -i '/^>/ s/.trimal.*//g' {}" ::: ${OUTDIR}/${species}_ExtractAlign/iter9/embossCons/*_cons.fa
            cat ${OUTDIR}/${species}_ExtractAlign/iter9/embossCons/*_cons.fa > ${OUTDIR}/${species}_Curated_Library/${species}_de_novo_repeat_library_iter9.fasta
            latestFile=${OUTDIR}/${species}_Curated_Library/${species}_de_novo_repeat_library_iter9.fasta
        else
            echo "$num iterations complete"
    fi
    
    
}

# Subprocess clusterDeNovo
clusterDeNovoPost()
{
    cd-hit-est -d 0 -aS 0.8 -c 0.8 -G 0 -g 1 -b 500 -r 1 -i $latestFile -o ${latestFile}.clustered.fa
    latestFile=${latestFile}.clustered.fa
}

# Subprocess BClass
BClass()
{
    cd ${OUTDIR}/${species}_Masked_de_novo_Repeats
    RepeatMasker -species $RepSpec -nolow -norna -lcambig -s -pa $ProcNum -dir ${OUTDIR}/${species}_Masked_de_novo_Repeats $latestFile
    awk '{OFS="\t"}{print $5, $5, $11}' ${OUTDIR}/${species}_Masked_de_novo_Repeats/${species}_de_novo_repeat_library_iter*.fasta.out | sort -u -k1,1 > TE_Class_Identities
    awk '{OFS="\t"}{gsub(/__.*/,"#",$2); print}' TE_Class_Identities | sed 's/#\t/#/g; s/^/sed -i "s|/g; s/\t/|/g; s/$/|g" /g' | sed "s|$|\"$latestFile\"|g" | grep "rnd" > TE_Class_Identities.script3
    chmod 777 ${OUTDIR}/${species}_Masked_de_novo_Repeats/TE_Class_Identities.script3
    ${OUTDIR}/${species}_Masked_de_novo_Repeats/TE_Class_Identities.script3
    rm ${OUTDIR}/${species}_Masked_de_novo_Repeats/TE_Class_Identities*
}

# Subprocess appLib
appLib()
{
    cd ${OUTDIR}/${species}_Curated_Library
    sed -i 's#___#/#g; s/__/#/g' $latestFile
    cat $RepSub $latestFile > ${species}_combined_library.fasta
}


# Subprocess novoMask
novoMask()
{
    cd ${OUTDIR}/${species}_RepeatMasker_Against_Custom_Library/
    RepeatMasker -lib ${OUTDIR}/${species}_Curated_Library/${species}_combined_library.fasta -cutoff 400 -nolow -norna -lcambig -s -a -pa $ProcNum -dir ${OUTDIR}/${species}_RepeatMasker_Against_Custom_Library/ $genome
}

# Subprocess calcDivRL
calcDivRL()
{
    cd ${OUTDIR}/${species}_RepeatLandscape
    genome_size=$(sed -n '4p' ${OUTDIR}/${species}_RepeatMasker_Against_Custom_Library/*.tbl | rev | cut -f1,1 -d ':' | rev | sed 's/ bp.*//g; s/ //g')
    align_file=$(readlink -f ${OUTDIR}/${species}_RepeatMasker_Against_Custom_Library/*.align)
    calcDivergenceFromAlign.pl -s ${species}.divsum $align_file
    div_file=$(readlink -f $OUTDIR/${species}_RepeatLandscape/${species}.divsum)
}

# Subprocess rcMergeRepeats
mergeRep()
{
    #cd ${OUTDIR}/${species}_mergedRepeats/
    #${SCRIPT_DIR}/rcMergeRepeats -f $genome -s $species -d ${OUTDIR}/${species}_mergedRepeats/ -u ${OUTDIR}/${species}_RepeatMasker_Against_Custom_Library/$(basename $genome).out -q ${OUTDIR}/${species}_RepeatMasker_Against_Custom_Library/$(basename $genome).tbl -t $ProcNum -b ${dict}
    mkdir ${OUTDIR}/${species}_mergedRepeats/looseMerge
    ${SCRIPT_DIR}/rcMergeRepeatsLoose -f $genome -s $species -d ${OUTDIR}/${species}_mergedRepeats/looseMerge -u ${OUTDIR}/${species}_RepeatMasker_Against_Custom_Library/$(basename $genome).out -q ${OUTDIR}/${species}_RepeatMasker_Against_Custom_Library/$(basename $genome).tbl -t $ProcNum -b ${dict}
}

# Subprocess pieChart
charts()
{
    cd ${OUTDIR}/${species}_summaryFiles/
    ${SCRIPT_DIR}/autoPie.sh -i ${OUTDIR}/${species}_mergedRepeats/looseMerge/${species}.filteredRepeats.bed -t ${OUTDIR}/${species}_RepeatMasker_Against_Custom_Library/$(basename $genome).tbl -p ${OUTDIR}/${species}_summaryFiles/${species}.summaryPie.pdf -o ${OUTDIR}/${species}_summaryFiles/${species}.highLevelCount.txt
    Rscript ${SCRIPT_DIR}/autoLand.R $div_file $genome_size $species ${OUTDIR}/${species}_summaryFiles/${species}.repeatLandscape.pdf
}

# Subprocess clusTErPluck
clusTErPluck()
{
    cd ${OUTDIR}/${species}_clusTErs/
    mergeBed -d ${dist} -i ${OUTDIR}/${species}_mergedRepeats/*.rmerge.gff | sed '1 i\Scaffold\tStart\tEnd' > ${OUTDIR}/${species}_clusTErs/${species}.clusTErs.bed
    clusterBed -d ${dist} -i ${OUTDIR}/${species}_mergedRepeats/*.rmerge.gff | sed '1 i\Scaffold\tSource\tRepeatFamily\tStart\tEnd\tScore\tStrand\tPhase\tAttributes\tClusterId' > ${OUTDIR}/${species}_clusTErs/${species}.detailedClusTErs.gff
}

# Subprocess sweepUp
sweepUp()
{
    cd ${OUTDIR}/${species}_summaryFiles/
    cp ${OUTDIR}/${species}_mergedRepeats/looseMerge/${species}.filteredRepeats.bed ${OUTDIR}/${species}_mergedRepeats/looseMerge/${species}.filteredRepeats.gff ${OUTDIR}/${species}_Curated_Library/${species}_combined_library.fasta $latestFile ${OUTDIR}/${species}_summaryFiles/
}

# Subprocess runningCow
runningCow()
{
    echo " ____________________
< $stage >
 --------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                
                ||----w |
                ||     ||"
}

# Subprocess GetTime
convertsecs() 
{
 h=$(bc <<< "${1}/3600")
 m=$(bc <<< "(${1}%3600)/60")
 s=$(bc <<< "${1}%60")
 printf "%02d:%02d:%05.2f\n" $h $m $s
}

# Subprocess Checks
Checks()
{
    if [ -z "$genome" ] || [ -z "$species" ] || [ -z "$directory" ] ; then
        usage; exit 1
    fi

    if [ -z "$ProcNum" ] ; then
        ProcNum=1; echo "$ProcNum Cores Will Be Used"
    fi

    if [[ -z "$RepSub" && -z "$RepSpec" ]]; then
	echo "Error: No RepeatMasker Species or Custom Repeat Library Specified"; exit 2
    fi

    if [ -z "$num" ] || [ -a "$num" -lt 3 -a "$num" -gt 10 ]; then
        num=5; echo "De Novo Sequences Will Be Extended Through $num Iterations"
    fi
    
    if [ -z "$dist" ]; then
        dist=100; echo "Clusters Will Be Considered When TEs Are <${dist}bp Apart"
    fi

    if [ -z "$Flank" ]; then
	Flank=1000; echo "Blast, Extract, Extend Process Will Add 1000bp to Each End in Each Iteration"
    fi

    if [ ! -d "$SCRIPT_DIR" ]; then
	echo "ERROR: Script directory variable not set, please run the configure script in the Earl Grey directory before attempting to run Earl Grey"; exit 1
    fi
    
    if [ "$CONDA_DEFAULT_ENV" == "earlGrey" ]; then
    	echo "Conda environment is active"
    else
    	echo "Conda environment is inactive, please activate conda environment before using Earl Grey"; exit 1
    fi
}

# Main #

while getopts g:s:l:o:t:f:r:i:d:h option
do
    case "${option}" 
        in
        g) genome=${OPTARG};;
        s) species=${OPTARG};;
        l) RepSub=${OPTARG};;
        o) directory=${OPTARG};;
        r) RepSpec=${OPTARG};;
        t) ProcNum=${OPTARG};;
        f) Flank=${OPTARG};;
        i) num=${OPTARG};;
        d) dist=${OPTARG};;
        h) usage; exit 1;; 
    esac
done

SECONDS=0

# Step 1

stage="Checking Parameters"
runningCow
SCRIPT_DIR=INSERTFILEPATHHERE
Checks
stage="Making Directories"
runningCow
makeDirectory
# Start Logs
exec > >(tee "${OUTDIR}/${species}EarlGrey.log") 2>&1
stage="Cleaning Genome"
runningCow
prepGenome
sleep 1


# Step 2

if [ ! -f ${OUTDIR}/${species}_RepeatMasker/*.masked ]; then
	if [ -z "$RepSpec" ]
		then
			stage="Running Initial Mask with Custom Library" && runningCow
			firstCustom
	elif [ ! -z "$RepSpec" ] 
		then
			stage="Getting RepeatMasker Sequences for $RepSpec and Saving as Fasta" && runningCow
			getRepeatMaskerFasta
			stage="Running Initial Mask with RepBase" && runningCow
			firstMask
	fi 
	sleep 1
else 
	stage="Genome has already been masked, skipping..."
	runningCow
	getRepeatMaskerFasta
	sleep 5
fi 

# Step 3
if [ ! -f ${OUTDIR}/${species}_Database/${species}-families.fa ]; then
	stage="Detecting New Repeats"
	runningCow
	buildDB
	deNovo1
	moveFiles
	stage="Clustering Sequences to Reduce Library Redundancy"
	runningCow
	clusterDeNovo
	sleep 1
else
	stage="De novo repeats have already been detected, skipping..."
	runningCow
	moveFiles
	stage="Clustering Sequences to Reduce Library Redundancy"
	runningCow
	clusterDeNovo
	sleep 1
fi

# Step 4 and 5
if [ ! -f ${OUTDIR}/${species}_Curated_Library/${species}_combined_library.fasta ]; then
        stage="BLASTing, Extracting, Extending for $num Iterations"
        runningCow
        BEE1
        Format1
        BEE2
        BEE3
        Iterations
        sleep 1
        stage="Building Species-Specific Library"
        runningCow
	clusterDeNovoPost
        BClass
        appLib
        sleep 1
else
        stage="BEE already completed, skipping..."
        runningCow
        sleep 1
fi

# Stage 6
if [ ! -f ${OUTDIR}/${species}_RepeatMasker_Against_Custom_Library/*.tbl ]; then
        stage="Identifying Repeats Using Species-Specific Library"
        runningCow
        novoMask
        calcDivRL
        sleep 1
else
        stage="Final masking already complete, skipping..."
        runningCow
        div_file=$(readlink -f $OUTDIR/${species}_RepeatLandscape/${species}.divsum)
        genome_size=$(sed -n '4p' ${OUTDIR}/${species}_RepeatMasker_Against_Custom_Library/*.tbl | rev | cut -f1,1 -d ':' | rev | sed 's/ bp.*//g; s/ //g')
        sleep 1
fi

# Stage 7
if [ ! -f ${OUTDIR}/${species}_mergedRepeats/looseMerge/${species}.filteredRepeats.bed ]; then
        stage="Running LTR_Finder and Defragmenting Repeats"
        runningCow
        mergeRep
        sleep 1
else
        stage="Repeats already defragmented, skipping..."
        runningCow
        sleep 1
fi


# Stage 8
stage="Generating Summary Plots"
runningCow
charts
sleep 1

# Stage 11
stage="Identifying TE Clusters and Member Sequences"
runningCow
clusTErPluck
sleep 1

# Stage 12 
stage="Tidying Directories and Organising Important Files"
runningCow
sweepUp
sleep 1

# Stage 13
time=$(convertsecs $SECONDS)
stage="Done in $time"
runningCow
sleep 5

# Stage 14
stage="De Novo Library, Combined Library, Summary Figures, and TE Quantifications in Standard Formats Can Be Found in ${OUTDIR}/${species}_summaryFiles/"
runningCow
sleep 5
