genome: 
  Danaus_plexippus: "data/NC_045808_EarlWorkshop.fasta"
  dummy: "data/dummy.fasta"
species: ["Danaus_plexippus", "dummy"]
output_dir: "results"
threads: 8
repeatmasker_species: ""  # e.g. "arthropoda" or "" for none
custom_library: ""        # path to custom library or "" for none
iterations: 10
flank: 1000
max_consensus_seqs: 20
min_consensus_seqs: 3
consensus_library : "results/combined_all_species.fa"
script_dir: "/Users/feurtey/Local_documents/Projects/EarlGrey_pangenome/earlGrey/scripts"
run_heliano: False
