
configfile: "config/config.yaml"

include: "rules/lib_construct.smk"
include: "rules/clustering.smk"
include: "rules/annotate_simple.smk"

GENOME = config["genome"]
SPECIES_LIST = config["species"]
OUTDIR = config["output_dir"] #os.path.join(config["output_dir"], f"{SPECIES}_EarlGrey")
THREADS = config["threads"]
REPSPEC = config["repeatmasker_species"]
CUSTOM_LIB = config["custom_library"]
ITER = config["iterations"]
FLANK = config["flank"]
MAX_SEQ = config["max_consensus_seqs"]
MIN_SEQ = config["min_consensus_seqs"]

rule all:
    input:
        expand(
            "{outdir}/{species}_EarlGrey/{species}_RepeatMasker_Against_Custom_Library/{species}.prep.masked",
            outdir=OUTDIR,
            species=SPECIES_LIST
        ),
        expand(
            "{outdir}/{species}_EarlGrey/{species}_RepeatMasker_Against_Custom_Library/{species}.prep.out",
            outdir=OUTDIR,
            species=SPECIES_LIST
        ),
        expand(
            "{outdir}/{species}_EarlGrey/{species}_RepeatMasker_Against_Custom_Library/{species}.prep.tbl",
            outdir=OUTDIR,
            species=SPECIES_LIST
        )

        #"results/combined_all_species.fa"
    
        # expand(
        #     "{outdir}/{species}_EarlGrey/{species}_summaryFiles/{species}-families.fa.strained",
        #     outdir=OUTDIR,
        #     species=SPECIES_LIST
        # )

# rule all:
#     input:
#         expand(
#             "{outdir}/{species}_EarlGrey/{species}_summaryFiles/{species}.highLevelCount.txt",
#             outdir=OUTDIR,
#             species=SPECIES_LIST
#         ),
#         expand(
#             "{outdir}/{species}_EarlGrey/{species}_summaryFiles/{species}.summaryPie.pdf",
#             outdir=OUTDIR,
#             species=SPECIES_LIST
#         ),
#         # Optional softmasked genome
#         expand(
#             "{outdir}/{species}_EarlGrey/{species}_summaryFiles/{species}.softmasked.fasta",
#             outdir=OUTDIR,
#             species=SPECIES_LIST
#         ) if SOFTMASK == "yes" else []